### ISSUE TITLE
XML -> JSON Liquid Maps

### ISSUE THREAD

**Issue by hrr** [skastberg/LiquidTransformation#2]
Logic App + Integration Account offers Liquid map transformation from XML to JSON, could we extend this to also support XML -> JSON maps?

Info: https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-enterprise-integration-liquid-transform

**Comment by skastberg** [comment]
Hello,

Yes, I think so. I will take a look at it over the weekend.

Samuel

**Comment by hrr** [comment]
A bit out of topic: 
I used to work with BizTalk intergrations quite a lot before (for a Swedish consultant company) and when it comes to mapping I used predominantly xslt for mapping. I'm working with something totally different now but got to lead a integration project since I have experience in it and that's also the reason I got into Liquid. What I miss right now is a simple way to test liquid maps locally, do you know if there are anything like the built-in visual studio xslt editor? Although the xslt editor was buggy it was still useful for quickly modifying and testing the maps in a graphic inteface.

**Comment by skastberg** [comment]
It's been a very long weekend ;-)
Sorry I missed to reply earlier. No there is no editor, I use Visual Studio Code with some extensions. 
When it comes to the issue itself, what kept me from solving this is that there are some extension tags I don't have access to as those aren't public. I close the issue for now but I keep it in mind for the future.
